name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.35.1-alpine

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: crystal spec

    - name: Build release
      run: shards --production build --release --static

    - name: Strip release
      run: strip bin/docker-release

    - uses: actions/upload-artifact@v2
      with:
        name: docker-deploy
        path: bin/docker-deploy
